### ISSUE TITLE
login.test.ts

### ISSUE THREAD

**Issue by shinYeongHyeon** [stevejkang/flex-work-check-in-out-automation#1]
login.test.ts 에서 BeforeEach 를 사용하면 await 한번으로 줄일 수 있어보여요

**Comment by stevejkang** [comment]
tc가 두 개인데 각 tc마다 beforeEach에서 api를 콜하기 보단, mocha에서 beforeAll 역할을 하는 before로 한 번만 api를 콜할 수 있게 처리해보겠습니다.
